# Site Settings
locale: "en-US"
title: "soderlind.dev"
title_separator: "-"
name: "Axel Söderlind"
description: "Blog and Portfolio"
url: "https://www.soderlind.dev"
baseurl: ""
repository: "asoderlind/asoderlind.github.io"

# Analytics
analytics:
  google:
    tracking_id: "G-ZVBXM2P6YW"

# Author
author:
  name: "Axel Söderlind"
  bio: "Engineering student on exchange @ Kyoto University"
  location: "Kyoto, Japan"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/asoderlind"
    - label: "GitHub"
      url: "https://github.com/asoderlind"
    - label: "Mail"
      url: "mailto:axel@soderlind.dev"

# Reading Files
include:
  - _pages
exclude:
  - vendor
  - .bundle
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Defaults
defaults:
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
